repo: github_repo_name
branch: github_repo_branch

configmap:
  enabled: false
  name: [a, b, c, ...]                          # Tên của configmap trong k8s và trong deployment để mount vào pod
  filename: [a, b, c, ...]                      # Tên của file trong configmap
  fileurl: ["/app/a", "/app/b", "/app/c", ...]  # Đường dẫn của file khi được mount vào trong pod

deployment:
  replicas: 1
  image: image
  tag: "tag"                                    # Tag cần được để trong "" nếu là số
  command: "command"
  port: 3000
  
service:
  enabled: true
  type: ClusterIP
  port: 3000
#  Dùng nlb thì cần loại LoadBalancer và annotations bên dưới
#  Dùng alb thì cần loại ClusterIP và Ingress
#  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-type: nlb
#    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
#    service.beta.kubernetes.io/aws-load-balancer-internal: true

ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
