repo: github_repo_name
branch: github_repo_branch

configmap:
  enabled: true
  name: [a, b, c, ...]                          # Tên của configmap trong k8s và trong deployment để mount vào pod
  filename: [a, b, c, ...]                      # Tên của file trong configmap
  fileurl: ["/app/a", "/app/b", "/app/c", ...]  # Đường dẫn của file khi được mount vào trong pod

deployment:
  replicas: 1
  image: image
  tag: "tag"                                    # Tag cần được để trong "" nếu là số
  port: 3000
  
service:
  enabled: true
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  class: nginx
  host: helm.pxd.com
  
