apiVersion: v1
entries:
  deployment-aws:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2024-09-23T09:20:35.288223504+07:00"
    description: A Helm chart for Kubernetes
    digest: 4bf0ce44606b2be003164fb926eca1787160779a895e572498027db4d021360e
    name: deployment-aws
    type: application
    urls:
    - https://phamxuanduong.github.io/helm/charts/deployment-aws/deployment-aws-0.1.0.tgz
    version: 0.1.0
  deployment-harvester:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2024-09-23T09:20:35.288864768+07:00"
    description: A Helm chart for Kubernetes
    digest: abfcfcbbce10bd4376ceb6b478ea39696a43276c5213ee40a09b4b0eb95d7520
    name: deployment-harvester
    type: application
    urls:
    - https://phamxuanduong.github.io/helm/charts/deployment-harvester/deployment-harvester-0.1.0.tgz
    version: 0.1.0
generated: "2024-09-23T09:20:35.287224737+07:00"
