apiVersion: v1
entries:
  deployment-aws:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2024-09-20T15:10:13.712116081+07:00"
    description: A Helm chart for Kubernetes
    digest: 4bf0ce44606b2be003164fb926eca1787160779a895e572498027db4d021360e
    name: deployment-aws
    type: application
    urls:
    - https://github.com/phamxuanduong/helm/charts/deployment-aws/deployment-aws-0.1.0.tgz
    version: 0.1.0
generated: "2024-09-20T15:10:13.711321868+07:00"
