apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.repo }}-{{ .Values.branch }}
  labels:
    app: {{ .Values.repo }}-{{ .Values.branch }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.repo }}-{{ .Values.branch }}
  template:
    metadata:
      labels:
        app: {{ .Values.repo }}-{{ .Values.branch }}
    spec:
{{- if .Values.configmap.enabled }}
      volumes:
{{- range $index, $name := .Values.configmap.name }}
      - name: {{ $name }}
        configMap:
          name: {{ $name }}
{{- end }}
{{- end }}
      containers:
      - name: {{ .Values.repo }}-{{ .Values.branch }}
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
{{- if .Values.deployment.command }}
        command: ["{{ .Values.deployment.command }}"]
{{- end }}
        ports:
        - containerPort: {{ .Values.deployment.port }}
{{- if .Values.configmap.enabled }}
        volumeMounts:
{{- range $index, $name := .Values.configmap.name }}
        - name: {{ $name }}
          mountPath: {{ index $.Values.configmap.fileurl $index }}
          subPath: {{ index $.Values.configmap.filename $index }}
{{- end }}
{{- end }}
