{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name | default (printf "%s-%s" .Values.repo .Values.branch) }}  # Nếu có giá trị ingress.name trong values.yaml, dùng nó; nếu không dùng repo-branch
  {{- if .Values.ingress.annotations }}
  annotations:  # Các annotations cho ingress (ví dụ cho ALB)
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}  # Mỗi annotation được lấy từ values.yaml
    {{- end }}
  {{- end }}
spec:
  ingressClassName: alb  # Sử dụng ALB làm ingress controller
  rules:
    - {{- if .Values.ingress.host }}  # Nếu có host trong values.yaml, thêm nó vào
      host: {{ .Values.ingress.host | quote }}  # Định nghĩa host cho ingress nếu có
      {{- end }}
      http:
        paths:
          - path: {{ .Values.ingress.path | default "/" }}  # Sử dụng path từ values.yaml nếu có; nếu không, mặc định là "/"
            pathType: Prefix  # Sử dụng kiểu đường dẫn Prefix
            backend:
              service:
                name: {{ .Values.ingress.serviceName | default (printf "%s-%s" .Values.repo .Values.branch) }}  # Nếu có serviceName trong ingress values.yaml, dùng nó; nếu không dùng repo-branch
                port:
                  number: {{ .Values.ingress.port | default .Values.service.port }}  # Nếu có port trong ingress values.yaml, dùng nó; nếu không dùng service.port
{{- end }}
