{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (printf "%s-%s" .Values.repo .Values.branch) }}  # Nếu có giá trị service.name trong values.yaml, dùng nó; nếu không dùng repo-branch
  {{- if .Values.service.annotations }}
  annotations:  # Thêm annotations nếu có
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}  # Mỗi annotation được render từ values.yaml
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}  # Kiểu service (ClusterIP, LoadBalancer, etc.)
  ports:
    - port: {{ .Values.service.port }}  # Cổng của service
      targetPort: {{ .Values.service.targetPort | default .Values.deployment.port }}  # Nếu có targetPort trong values.yaml, dùng nó; nếu không dùng deployment.port
  selector:
    app: {{ .Values.repo }}-{{ .Values.branch }}  # Chọn pod dựa trên nhãn app
{{- end }}
